version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=RedisExample
    ports:
      - "5432:5432"
    networks:
      - redis

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=secret
      - REDIS_DB=1 #default 0 - 16 databases, indexed 0–15.
    ports:
      - "6379:6379"
    networks:
      - redis

networks:
  redis:
    driver: bridge